export const alumniInfo = [
  {
    NAME: "Tiffany Soga",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2015",
    VOICE_PART: "Alto",
    COURSE: "MA English",
    POSITION: "-",
  },
  {
    NAME: "Lucy Harries",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2015",
    VOICE_PART: "Soprano",
    COURSE: "French and Italian",
    POSITION: "-",
  },
  {
    NAME: "Mhairi Angus",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2015",
    VOICE_PART: "Soprano",
    COURSE: "Theatre and English",
    POSITION: "-",
  },
  {
    NAME: "George Bracegirdle",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2015",
    VOICE_PART: "Tenor",
    COURSE: "Veterinary Science",
    POSITION: "-",
  },
  {
    NAME: "Eve Robertson-Waters",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Soprano",
    COURSE: "Medicine",
    POSITION: "Founder",
  },
  {
    NAME: "Aliak Bedirian",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Alto",
    COURSE: "Music",
    POSITION: "Musical Director (2015-2016)",
  },
  {
    NAME: "Gemma Davies",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Alto",
    COURSE: "English and Classical Studies",
    POSITION: "Secretary (2015-2016)",
  },
  {
    NAME: "Chris Georgiou",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Bass",
    COURSE: "Music",
    POSITION: "-",
  },
  {
    NAME: "Masheyr Devaser",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Tenor",
    COURSE: "Mechanical Engineering",
    POSITION: "Marketing Manager (2015-2016)",
  },
  {
    NAME: "Rohan Garwood",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2018",
    VOICE_PART: "Tenor",
    COURSE: "German and French",
    POSITION: "Social Sec (2015-2016)",
  },
  {
    NAME: "Harry Loble",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Bass",
    COURSE: "Music",
    POSITION: "-",
  },
  {
    NAME: "Scott Lechleiter",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "VP",
    COURSE: "Biochemistry",
    POSITION: "-",
  },
  {
    NAME: "Bea Paterson-Achenbach",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2016",
    VOICE_PART: "Alto",
    COURSE: "English Literature and Philosophy",
    POSITION: "Tour Manager (2015-2016)",
  },
  {
    NAME: "Rafaella Barratt",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2018",
    VOICE_PART: "Soprano",
    COURSE: "Medicine",
    POSITION: "Founder, President (2015-2016)",
  },
  {
    NAME: "Joe Pickin",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2017",
    VOICE_PART: "Tenor",
    COURSE: "Mathematics",
    POSITION:
      "Founder, Musical Director (2014-2016), Treasurer (2015-2016), Group Manager (2016-2017)",
  },
  {
    NAME: "Stanford",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2017",
    VOICE_PART: "Bass",
    COURSE: "Politics",
    POSITION: "-",
  },
  {
    NAME: "Dan Mailer",
    YEAR_JOINED: "2014",
    YEAR_LEFT: "2018",
    VOICE_PART: "Bass",
    COURSE: "Music",
    POSITION:
      "Tour Manager (2015-2016), Performance Director (2015-2016), Musical Director (2016-2017), Business Manager (2017-2018)",
  },
  {
    NAME: "Sushmi Jay",
    YEAR_JOINED: "2015",
    YEAR_LEFT: "2016",
    VOICE_PART: "Soprano",
    COURSE: "Dentistry",
    POSITION: "-",
  },
  {
    NAME: "Alice Tyler",
    YEAR_JOINED: "2015",
    YEAR_LEFT: "2017",
    VOICE_PART: "Alto",
    COURSE: "Theatre",
    POSITION: "-",
  },
  {
    NAME: "Matthew Belsey",
    YEAR_JOINED: "2015",
    YEAR_LEFT: "2018",
    VOICE_PART: "Tenor",
    COURSE: "Mathematics",
    POSITION: "Business Manager (2016-2017)",
  },
  {
    NAME: "Eleanor Leaper",
    YEAR_JOINED: "2015",
    YEAR_LEFT: "2018",
    VOICE_PART: "Soprano",
    COURSE: "Music",
    POSITION:
      "Tour Manager (2016-2017), Performance Director (2016-2017), Musical Director (2017-2018)",
  },
  {
    NAME: "Charlotte Regan",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "Soprano",
    COURSE: "Film and English",
    POSITION: "Marketing Manager (2016-2017), Group Manager (2017-2019)",
  },
  {
    NAME: "Yassie Gezer",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2018",
    VOICE_PART: "Soprano",
    COURSE: "Music",
    POSITION: "-",
  },
  {
    NAME: "Rachael Mailer",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "Alto",
    COURSE: "Theatre and Film",
    POSITION: "Marketing Manager (2017-2018)",
  },
  {
    NAME: "Kathryn Case",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "Alto",
    COURSE: "Film and German",
    POSITION: "Marketing Manager (2018-2019)",
  },
  {
    NAME: "Charlie Walker",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2018",
    VOICE_PART: "Alto",
    COURSE: "English",
    POSITION: "-",
  },
  {
    NAME: "James Dempsey",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "VP",
    COURSE: "Computer Science and Mathematics",
    POSITION: "Web Developer 2021 - present",
  },
  {
    NAME: "Sam Walter",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "Tenor",
    COURSE: "Physics",
    POSITION:
      "Performance Director (2017-2018), Assistant Performance Director (2018-2019)",
  },
  {
    NAME: "Jonny Simon",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "Baritone",
    COURSE: "Music",
    POSITION: "Musical Director (2018-2019)",
  },
  {
    NAME: "Benedict Piers Rowan Harwood",
    YEAR_JOINED: "2016",
    YEAR_LEFT: "2019",
    VOICE_PART: "Baritone",
    COURSE: "History",
    POSITION: "Tour Manager (2017-2018), Business Manager (2018-2019)",
  },
  {
    NAME: "Cassie Jackson",
    YEAR_JOINED: "2017",
    YEAR_LEFT: "2018",
    VOICE_PART: "Alto",
    COURSE: "French and Spanish",
    POSITION: "-",
  },
  {
    NAME: "Bryan Palacio",
    YEAR_JOINED: "2017",
    YEAR_LEFT: "2018",
    VOICE_PART: "Tenor",
    COURSE: "Mathematics",
    POSITION: "-",
  },
  {
    NAME: "Robbie Armstrong",
    YEAR_JOINED: "2017",
    YEAR_LEFT: "-",
    VOICE_PART: "Baritone",
    COURSE: "Biology",
    POSITION:
      "Tour Manager (2018-2019), Group manager (2019-2020), Musical Director (2020-2021)",
  },
  {
    NAME: "Alessia Doyle",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Alto",
    COURSE: "French and Italian",
    POSITION: "Performance Director (2018-2019), Marketing Manager (2020-2021)",
  },
  {
    NAME: "Naomi Adams",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Alto",
    COURSE: "Law",
    POSITION: "-",
  },
  {
    NAME: "Rachel Xuereb",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Soprano",
    COURSE: "Sociology",
    POSITION:
      "Tour Manager (2019-2020), Assistant Performance Director (2019-2020)",
  },
  {
    NAME: "Emily Hall",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Soprano",
    COURSE: "English Literature",
    POSITION: "Group Manager (2020-2021)",
  },
  {
    NAME: "Frances McGirr",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Soprano",
    COURSE: "Music",
    POSITION: "Musical Director (2019-2020)",
  },
  {
    NAME: "Oscar Andrusier",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Tenor",
    COURSE: "Medicine",
    POSITION: "-",
  },
  {
    NAME: "Maurice Brook",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Tenor",
    COURSE: "Physiological Science",
    POSITION: "Business Manager (2019-2020)",
  },
  {
    NAME: "Jack Prowse",
    YEAR_JOINED: "2018",
    YEAR_LEFT: "-",
    VOICE_PART: "Baritone",
    COURSE: "French and German",
    POSITION: "Performance Director (2019-2020)",
  },
  {
    NAME: "Himari Takata",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Soprano",
    COURSE: "Pharmacology",
    POSITION: "-",
  },
  {
    NAME: "Rosa Witts",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Alto",
    COURSE: "Music",
    POSITION: "Assistant Musical Director (2020-2021)",
  },
  {
    NAME: "Jasmine Bingham",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Alto",
    COURSE: "Music and Spanish",
    POSITION: "-",
  },
  {
    NAME: "Zoe Freeman",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Alto",
    COURSE: "History",
    POSITION: "-",
  },
  {
    NAME: "Cameron Browne",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Tenor",
    COURSE: "Mechanical Engineering",
    POSITION: "-",
  },
  {
    NAME: "Ryan Blyth",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Baritone",
    COURSE: "Education Studies",
    POSITION: "-",
  },
  {
    NAME: "Mikey Galvin",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "Baritone",
    COURSE: "Law",
    POSITION: "Marketing Manager (2019-2020)",
  },
  {
    NAME: "Nathan Cave",
    YEAR_JOINED: "2019",
    YEAR_LEFT: "-",
    VOICE_PART: "VP",
    COURSE: "Mathematics",
    POSITION: "Business Manager (2020-2021)",
  },
];
